theme: jekyll-theme-minimal
title: forwardcomputers.com
twitter: https://img.shields.io/twitter/url/https/fwdcomputers.svg?style=social
description: 
lang: 
logo:
google_analytics: 
show_downloads:
github:
  owner_name:
  owner_url:
  repository_name:
  repository_url:
  zip_url: 
  tar_url:
