theme: jekyll-theme-cayman
title: forwardcomputers.com
description: 
lang: 
google_analytics: 
show_downloads:
github:
  is_project_page:
  owner_name:
  owner_url:
  repository_name:
  repository_url:
  zip_url: 
  tar_url:
