theme: jekyll-theme-minimal
title: forwardcomputers.com
twitter: https://twitter.com/fwdcomputers
description: 
lang: 
logo:
google_analytics: 
show_downloads:
social:
  name: forwardcomputers
  links:
    - https://twitter.com/fwdcomputers
    - https://github.com/forwardcomputers
twitter:
  username: fwdcomputers
  card: summary
github:
  owner_name:
  owner_url:
  repository_name:
  repository_url:
  zip_url: 
  tar_url:
