name: Build other docker images

on:
  repository_dispatch:
    types:
      - build_other_docker_images
#  schedule:
#    # Times are in UTC
#    - cron:  '0 9 * * *'
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.LP_DOCKER_USERNAME }}
          password: ${{ secrets.LP_DOCKER_TOKEN }}

      - name: set up qemu
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: get versions
        run: |
          set -x
          ## obico-server
          _app=obico-server
          echo "_repo={{ secrets.LP_DOCKER_USERNAME }}/${ app }" >> $GITHUB_ENV
          set +e
          _local=$( cat "script/${ _app }.sha" )
          set -e
          _remote=$( git ls-remote "https://github.com/TheSpaghettiDetective/${ _app }.git" HEAD | cut -f1 )
          if [ "${ _local }" = "${ _remote }" ]; then
            echo "_build=false" >> $GITHUB_ENV
          else
            echo "${ _remote }" > "script/${env._app}.sha"
            git config --local user.email "alim@forwardcomputers.com"
            git config --local user.name "Ali Mustakim"
            git add .
            git commit -a -m "github actions update"
            git push
            echo "_build=true" >> $GITHUB_ENV
          fi

      - name: checkout ${{ env._repo }}
        if: env._build
        uses: actions/checkout@v4
        with:
          repository: TheSpaghettiDetective/obico-server

      - name: Build and push ${{ env._repo }}
        if: env._build
        uses: docker/build-push-action@v5
        with:
          context: backend
          platforms: linux/amd64
          push: true
          tags: ${{ env._repo }}:latest
