name: versions

on:
  repository_dispatch:
    types:
      - versions
  schedule:
    # Times are in UTC
    - cron:  '10 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get versions
        run: |
          curl -sLo ~/am-epg "https://github.com/forwardcomputers/bin/raw/main/am-epg"
          chmod +x ~/am-epg
          ~/am-epg

      - name: commit and push
        run: |
          git config --local user.email "alim@forwardcomputers.com"
          git config --local user.name "Ali Mustakim"
          git add .
          git diff-index --quiet HEAD || git commit -a -m "github actions update"
          git push origin
