name: forwardcomputers

on:
  push:
  schedule:
    # Times are in UTC, this job is run daily @ 14HRS = 9AM EST, 20HRS = 3PM EST
    - cron: "0 14,20 * * *"
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build readme file
        run: |
          script/build.sh
          git config --local user.email "alim@forwardcomputers.com"
          git config --local user.name "Ali Mustakim"
          git add .
          git diff-index --quiet HEAD || git commit -a -m "github actions update [skip ci]"
          git push origin
